### ISSUE TITLE
Custom panel

### ISSUE THREAD

**Issue by ridwan-shaikh** [sigven/cpsr#22]
Hi Sigven,

This is more of a question/feature request than an issue. Would it be possible to use a custom panel in CPSR?

I was thinking I could create a custom bed file in pcgr/data/grch37/virtual_panels/ but I noticed your virtual panels are annotated, so I was not too sure if the annotations were a requirement or not, or if having a custom bed file would create issues further down the line?

Regards,
Ridwan

**Comment by sigven** [comment]
Hi @ridwan-shaikh,
Thanks for reaching out. Submitting a custom panel (i.e. a BED file) in CPSR is not currently supported. Please also keep in mind the scope of the tool, to screen for cancer predisposition variants. I believe the current panels, and specifically panel 0 (exploratory), are not missing many genes that are know to be associated with cancer predisposition. If you have suggestions for novel candidates, please lay them forward. If you want to screen for other disease genes, or genes not related to cancer predisposition, this is really beyond the scope of the tool.

best,
Sigve

**Comment by ridwan-shaikh** [comment]
Hi Sigve,

Thanks for information. So the issue I noticed was there were a few genes in our custom clinically validated paediatric panel we run as part of the Stratified Medicines Paediatrics programme UK (SMPeads) [(see paper here)](https://www.sciencedirect.com/science/article/pii/S0959804919304460?via%3Dihub) where we had found germline mutations (that would most likely be VUS) but are not a part of the exploratory panel 0, and subsequently on any other panel and therefore not reported on. This panel is designed for relapsed and refractory patients but we do report on secondary findings. Any advice on how to best approach these situations? More than likely the secondary findings we report will probably be VUS, but it would be nice if they could also be included in the report.

Maybe this is a situations others may find if they are running custom panels in their centres?

**Comment by sigven** [comment]
Hi Ridwan,
Totally see your point. And as you say, I believe others will be faced with the same challenge, considering the various custom-made panels that is being made. I will try to think of a strategy to support this, primarily like you suggested; as a BED file that is provided by the user, with a name defined in the configuration file. It might not be as much work as I was initially thinking. Will put this issue as an enhancement for now (need to develop and test, if you can provide an example BED file + VCF, with assembly spec, that would be helpful)

best,
Sigve

**Comment by ridwan-shaikh** [comment]
Hi Sigve,

Would you mind if I sent only a watered down version of the bed file? The bed file is company property so bound by datasharing rules unfortunately.

Sorry to be a pain.

Regards,
Ridwan

**Comment by sigven** [comment]
Sure, been playing with this today, so happy to have a go at a testset.

best,
Sigve

**Comment by sigven** [comment]
Having looked at this, I may put a restriction on the BED file suggesting that the gene symbol of interest is provided along with the actual genomic intervals. Considering the overlap between distinct genes due to regulatory regions (upstream of TSS), it would probably be necessary also to provide the desired targets (i.e. gene symbol). This in order to avoid a large number of irrelevant genes to be shown in the report.

**Comment by kokyriakidis** [comment]
Hi @sigven !

Could you please show me 2-3 lines of thes bed file, so I am sure I do it the right way?

**Comment by ridwan-shaikh** [comment]
Hi Sigve,

My apologies, I really don't know how this escaped by mind, or my endless list of things to do. I have a test bed file and a test vcf for you. How shall I send it to you?

Regards,
Ridwan

**Comment by sigven** [comment]
Dear @ridwan-shaikh,
Sorry for my late response to this. If you could share through Dropbox etc. that would be convenient, otherwise try sigven AT ifi . uio .no. 

@kokyriakidis:

BED file should look like this (dummy example, gene regions do not make any sense):

chr1   1    10000    BRCA1
chr2   1    10000    ATM


Best,
Sigve

**Comment by ohofmann** [comment]
Hi Sigve - I am going to +1 this but from a different perspective: I'd love to restrict the reported gene list. E.g., report on just a subset of genes present in the panel 0 list. We can work around this by submitting the submitted VCF to just the regions of interest, I suppose.

**Comment by sigven** [comment]
Hi Oliver, I think your strategy would make a lot of sense actually (and my life somewhat easier:-)) Accepting _any_ target gene is really not something I wanted to support, since this tool is dedicated for cancer predisposition. The strategy may rather be to increase the panel 0 with any gene of potential relevance for cancer risk, and then restrict from that one.
