### ISSUE TITLE
Missed variant due to transcript pick?

### ISSUE THREAD

**Issue by vladsaveliev** [sigven/cpsr#26]
Hi Sigve, attaching a variant that was picked with CPSR 0.4.0, but missed in 0.5.2 - I'm struggling to understand why: [germline_GJB2_13_20189473.vcf.gz](https://github.com/sigven/cpsr/files/4137615/germline_GJB2_13_20189473.vcf.gz)

The variant has multiple transcript annotations. In 0.4.0, there are 4:
ENST00000382844 - missense_variant, protein_coding
ENST00000382848 - missense_variant, protein_coding - 0.4.0 picked this one
ENST00000624851 - upstream_gene_variant, TEC
ENST00000645189 - missense_variant, protein_coding

In 0.5.2, there are 3:
ENST00000382844 - missense_variant, protein_coding
ENST00000382848 - missense_variant, protein_coding
ENST00000624851 - upstream_gene_variant, TEC - 0.5.2 uses this one

In both versions, there is a choice of a missense coding variant, and 0.4.0 picks one, however 0.5.2 choses an upstream version and doesn't show the variant in the report.

Not sure if `vep_pick_order` is relevant here. For 0.4.0 runs, I use in the config toml:
```
vep_pick_order = "rank,appris,biotype,tsl,ccds,canonical,length"
```
For 0.5.2, I use same plus mane:
```
vep_pick_order = "rank,appris,biotype,tsl,ccds,canonical,length,mane"
```
So I would guess it should pick based on rank first, meaning that protein_coding should have a higher priority. But I also tried 0.5.2 with a default pick order - same result.

Wondering if you know why a protein coding transcript is not picked?

The command I'm using:
```
cpsr.py germline_GJB2_13_20189473.vcf.gz pcgr output grch38 --panel_id 0 cpsr.toml SBJ00203__SBJ00203_MDX190232_L1901042-normal  --no-docker --force_overwrite --no_vcf_validate --debug
```

Where the toml for 0.5.2 is: [cpsr.toml.zip](https://github.com/sigven/cpsr/files/4137644/cpsr.toml.zip)

**Comment by sigven** [comment]
Thanks for the notification, Vlad. Will have a look into it!

**Comment by vladsaveliev** [comment]
Also, wondering why is this only executed for CPSR?

```
         if cpsr is True:
            block_idx = annoutils.get_correct_cpg_transcript(vep_csq_records)
```

I'm seeing a similar issue for PCGR with a coding variant in TNXB reported as a downstream event in AL662884.2:

<img width="1170" alt="Screen Shot 2020-02-13 at 15 47 50" src="https://user-images.githubusercontent.com/1575412/74408715-80abb480-4e78-11ea-8120-b24eedf75a78.png">

Thought it might get fixed by the same fix, but it's not.

Attaching the variant VCF: 
[TNXB.vcf.gz](https://github.com/sigven/cpsr/files/4196867/TNXB.vcf.gz)

**Comment by sigven** [comment]
Hi Vlad,

Regarding the GJB2 case (this is somewhat complicated, here is a shot):

The first part is due to the fact that CPSR is targeted towards specific genes of interest. This means that we need to capture not only one primary transcript consequence (since a variant may be annotated with multiple genes, and we want to report the consequence related to the targeted gene). Basically, we need the primary transcript consequence pr. gene (`--flag_pick_allele_gene` option in VEP). The primary transcript (for each gene) will then be based on the `--pick_order` option. Since the CPSR report is still reporting a single consequence pr. variant as its main output, the internal software needs to resolve these cases where VEP has picked more than one consequence (i.e. `get_correct_cpg_transcript`, "if cpsr is True"). The `get_correct_cpg_transcript` looks through the variants and reports the variant consequence for which the associated gene is in fact related to the targeted genes (i.e. part of a panel or the global set). There was a bug in this code, but I have fixed that now, and will commit these change.

[GJB2_13_20189473.cpsr.snvs_indels.tiers.grch38.tsv.gz](https://github.com/sigven/cpsr/files/4203904/GJB2_13_20189473.cpsr.snvs_indels.tiers.grch38.tsv.gz)


For PCGR, I believe that `--flag_pick_allele` will be sufficient, (currently it's the same as CPSR (`--flag_pick_allele_gene`), since there is no prior prioritization as to which genes are most important. And accordingly, that the VEP pick order will form the basis for how the primary consequence is picked (and also resolve the case of consequences from different genes). 

That being said, I am like you struggling to see how the TNXB variant get's annotated as it is now, it seems to be reported as an inframe TNXB deletion when using the VEP web interface, and that gene carries a number of properties that would make it rank above the lncRNA gene, but when I run VEP locally (v99) even without specifying the `--pick-order` (which I then would expect to behave using it's default behavior), it still chooses the downstream_gene_variant as the main consequence block. Will continue to figure out how this can take place. 

Sigve

**Comment by sigven** [comment]
Regarding PCGR, I think we may use this pick order as the default one:

`vep_pick_order = "appris,biotype,canonical,ccds,rank,tsl,length,mane"`
or even
`vep_pick_order = "biotype,appris,canonical,ccds,rank,tsl,length,mane"`

Reason I think rank should not be put at the front is that I think focusing on the relevant gene/transcripts should be given more importance than the severity of the consequence (i.e. so that a missense_variant in an obscure gene would not be prioritized over a non-coding variant in a well-established and important transcript. I hope this ranking will ensure that when consequences from two different genes are encountered, the functional nature of the gene is prioritized, then the importance for the given transcript(s) within that gene, and then ranks (consequence type).

**Comment by vladsaveliev** [comment]
Thanks so much Sigve for your investigation and for the CPSR fix. This is super helpful.

Regarding moving "rank" down the list, I remember there was an issue that made me play with moving it up in the first place https://github.com/sigven/pcgr/issues/79 Need to go back to that case and see how the order "biotype,appris,canonical,ccds,rank,tsl,length,mane" will affect it.

Just to make sure, am I understanding correctly that the TNXB prioritization issue is not relevant to vep_pick_order, so moving "rank" down does not solve it?

Vlad

**Comment by vladsaveliev** [comment]
Sigve, still not sure about TNXB in PCGR.

The issue is _not_ that a missense variant in an obscure gene is prioritized over a non-coding variant of an important gene. It's that a missense variant in a well-established TNXB is reported as a non-coding variant in an obscure AL662884.2.

**Comment by vladsaveliev** [comment]
Played a bit with VEP options. Apparently using `flag_pick_allele` for PCGR helps here. Since PCGR doesn't use a procedure to prioritize genes like CPSR does, we need to make sure there is one consequence selected per event, otherwise VEP picks multiple ones and PCGR end up using a less relevant one.

**Comment by sigven** [comment]
This makes sense to me at least (I get confused at times with how the ordering actually works, and then adding two potential consequences on top of that will not make it easier.. ). I'll move from --flag_pick_allele_gene to flag_pick_allele in PCGR to ensure this will not pose a problem.

**Comment by vladsaveliev** [comment]
Fantastic, thanks Sigve :) I guess all good now with this issue
