### ISSUE TITLE
Installation Instructions Only Describe Conda

### ISSUE THREAD

**Issue by DarioS** [sigven/cpsr#45]
> We recommend conda as the simplest framework to install PCGR and CPSR

This suggests there are other ways to do it. Could they be added to the information web page? I am using a department server which has `pip` and `virtualenv` but not `conda` available to me. How would I install this software in such a scenario?

```
~$ virtualenv --version
virtualenv 20.4.0+ds from /usr/lib/python3/dist-packages/virtualenv/__init__.py
~$ pip --version
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
~$ conda
-bash: conda: command not found
```

**Comment by pdiakumis** [comment]
Hi Dario!
Sorry, we should probably reword that. I guess it's simpler to run CPSR/PCGR via conda than Docker, for example, especially on HPC.

Since CPSR/PCGR use a variety of tools in addition to R/Python dependencies (such as bedtools/vcfanno/vcf2maf), we've found conda to be the more efficient way to install it. `pip` for instance wouldn't be able to install `bedtools`.

Another great thing about conda is that you can install it and the various conda pkgs in your own home directory on HPC, without requiring permission from the HPC admin for instance. The PCGR installation docs have an example walkthrough at <https://sigven.github.io/pcgr/articles/installation.html#condasetup>. For more details the conda docs would be the better resource of course.

Let me know if you have any issues with that, happy to follow up via email if you want more help (<first><last> at gmail.com).

**Comment by DarioS** [comment]
Ah, O.K. I'll do a home directory install. Yes, please reword it for clarity.
